// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poketext.Models;

#nullable disable

namespace Poketext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726040608_AddQuantityToUserPokemon")]
    partial class AddQuantityToUserPokemon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Poketext.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/Images/pokemon/Bulbasaur.png",
                            Name = "Bulbasaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/Images/pokemon/Ivysaur.png",
                            Name = "Ivysaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/Images/pokemon/Venusaur.png",
                            Name = "Venusaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/Images/pokemon/Charmander.png",
                            Name = "Charmander",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/Images/pokemon/Charmeleon.png",
                            Name = "Charmeleon",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/Images/pokemon/Charizard.png",
                            Name = "Charizard",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/Images/pokemon/Squirtle.png",
                            Name = "Squirtle",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/Images/pokemon/Wartortle.png",
                            Name = "Wartortle",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/Images/pokemon/Blastoise.png",
                            Name = "Blastoise",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/Images/pokemon/Caterpie.png",
                            Name = "Caterpie",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/Images/pokemon/Metapod.png",
                            Name = "Metapod",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/Images/pokemon/Butterfree.png",
                            Name = "Butterfree",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/Images/pokemon/Pikachu.png",
                            Name = "Pikachu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/Images/pokemon/Raichu.png",
                            Name = "Raichu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/Images/pokemon/Jigglypuff.png",
                            Name = "Jigglypuff",
                            Type = "Fairy"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/Images/pokemon/Meowth.png",
                            Name = "Meowth",
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/Images/pokemon/Psyduck.png",
                            Name = "Psyduck",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/Images/pokemon/Machop.png",
                            Name = "Machop",
                            Type = "Fighting"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/Images/pokemon/Gengar.png",
                            Name = "Gengar",
                            Type = "Ghost"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/Images/pokemon/Eevee.png",
                            Name = "Eevee",
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Poketext.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapturedPokemon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Poketext.Models.UserPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId", "PokemonId")
                        .IsUnique();

                    b.ToTable("UserPokemons");
                });

            modelBuilder.Entity("Poketext.Models.UserPokemon", b =>
                {
                    b.HasOne("Poketext.Models.Pokemon", "Pokemon")
                        .WithMany("UserPokemons")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poketext.Models.User", "User")
                        .WithMany("UserPokemons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Poketext.Models.Pokemon", b =>
                {
                    b.Navigation("UserPokemons");
                });

            modelBuilder.Entity("Poketext.Models.User", b =>
                {
                    b.Navigation("UserPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
