// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poketext.Models;

#nullable disable

namespace Poketext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Poketext.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulbasaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ivysaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venusaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Charmander",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charmeleon",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charizard",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Squirtle",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wartortle",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Blastoise",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Caterpie",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Metapod",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Butterfree",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pikachu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Raichu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jigglypuff",
                            Type = "Fairy"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Meowth",
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Psyduck",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Machop",
                            Type = "Fighting"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Gengar",
                            Type = "Ghost"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Eevee",
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Poketext.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapturedPokemon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Poketext.Models.UserPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId", "PokemonId")
                        .IsUnique();

                    b.ToTable("UserPokemons");
                });

            modelBuilder.Entity("Poketext.Models.UserPokemon", b =>
                {
                    b.HasOne("Poketext.Models.Pokemon", "Pokemon")
                        .WithMany("UserPokemons")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poketext.Models.User", "User")
                        .WithMany("UserPokemons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Poketext.Models.Pokemon", b =>
                {
                    b.Navigation("UserPokemons");
                });

            modelBuilder.Entity("Poketext.Models.User", b =>
                {
                    b.Navigation("UserPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
